CREATE DATABASE EXEMPLOAULA01

USE EXEMPLOAULA01

CREATE TABLE PRODUTO(
COD_PRODUTO INT PRIMARY KEY NOT NULL,
NOME VARCHAR(50),
PRECO_CUSTO DECIMAL(10,2),
PRECO_VENDA DECIMAL(10,2),
CATEGORIA INT
)

INSERT INTO PRODUTO(COD_PRODUTO,NOME,PRECO_CUSTO,PRECO_VENDA,CATEGORIA)VALUES(001,'MOUSE',10.00,15.00,1)
INSERT INTO PRODUTO(COD_PRODUTO,NOME,PRECO_CUSTO,PRECO_VENDA,CATEGORIA)VALUES(002,'TABLET',100.00,150.00,2)
INSERT INTO PRODUTO(COD_PRODUTO,NOME,PRECO_CUSTO,PRECO_VENDA,CATEGORIA)VALUES(003,'CADERNO',20.00,35.00,3)
INSERT INTO PRODUTO(COD_PRODUTO,NOME,PRECO_CUSTO,PRECO_VENDA,CATEGORIA)VALUES(004,'LAPIS',2.50,4.00,3)
INSERT INTO PRODUTO(COD_PRODUTO,NOME,PRECO_CUSTO,PRECO_VENDA,CATEGORIA)VALUES(005,'TECLADO',20.00,30.00,1)

SELECT * FROM PRODUTO

/*usuamos WHERE para filtrar os dados de um comando sql. */
/*EXPRESSÕES LÓGIGAS*/
/*IGUALDADE*/

SELECT NOME,CATEGORIA 
FROM PRODUTO 
WHERE CATEGORIA = 2 AND PRECO_CUSTO > 20.00

/*DIFERENÇA*/

SELECT 
NOME,
PRECO_CUSTO,
PRECO_VENDA
FROM 
PRODUTO
WHERE PRECO_VENDA <> 10.00

/*MAIOR QUE / MENOR QUE */

SELECT 
NOME,
PRECO_CUSTO
FROM 
PRODUTO
WHERE PRECO_CUSTO <= 10.00
/*WHERE PRECO_CUSTO >= 10.00*/
SELECT 
NOME,
PRECO_VENDA
FROM 
PRODUTO
WHERE PRECO_VENDA BETWEEN 50.00 AND 150.00

/*LIKE */
SELECT 
NOME,
PRECO_VENDA
FROM 
PRODUTO
WHERE NOME LIKE '%CA%'

/*IN */
SELECT 
NOME
FROM 
PRODUTO
WHERE NOME IN ('TABLET','MOUSE')

/*AND */
SELECT 
COD_PRODUTO,
NOME,
PRECO_CUSTO,
PRECO_VENDA
FROM 
PRODUTO
WHERE PRECO_VENDA >=(PRECO_CUSTO + (PRECO_CUSTO * 0.1)) AND CATEGORIA =3


SELECT 
COD_PRODUTO,
NOME
FROM 
PRODUTO
WHERE (CATEGORIA =2 OR PRECO_VENDA > 10) AND PRECO_CUSTO < 20.00

/*ORDENAÇÃO BY E DESC */
 SELECT
 COD_PRODUTO,
 NOME
 FROM 
 PRODUTO
 ORDER BY NOME


