/* CRIANDO O BANCO DE DADOS DE UMA LOJA */
CREATE DATABASE BDLOJA
/* USANDO O BANCO DE DADOS DE UMA LOJA */
USE BDLOJA

/* CRIANDO AS TABELAS DO BANCO BDLOJA */

CREATE TABLE FUNCIONARIO(
COD_FUNCIONARIO INT PRIMARY KEY IDENTITY,
NOME_FUNCIONARIO VARCHAR(50),
USUARIO VARCHAR(50),
SENHA VARCHAR(50)
)
CREATE TABLE CLIENTE(
COD_CLIENTE INT PRIMARY KEY,
NOME_CLIENTE VARCHAR(50),
CPF VARCHAR(20)
)

CREATE TABLE PRODUTO(
COD_PRODUTO INT PRIMARY KEY,
NOME_PRODUTO VARCHAR(50),
)
CREATE TABLE PEDIDO(
COD_PEDIDO INT PRIMARY KEY,
VALOR DECIMAL(10,2),
QUANTIDADE INT,
FK_COD_PRODUTO INT,
FK_COD_CLIENTE INT
FOREIGN KEY(FK_COD_PRODUTO) REFERENCES PRODUTO(COD_PRODUTO),
FOREIGN KEY(FK_COD_CLIENTE) REFERENCES CLIENTE(COD_CLIENTE)
)
/* CONSULTANDO AS TABELAS DO BANCO BDLOJA */

SELECT * FROM FUNCIONARIO
SELECT * FROM CLIENTE
SELECT * FROM PRODUTO
SELECT * FROM PEDIDO

/* INSERINDO INFORMAÇÕES NAS TABELAS */

INSERT INTO FUNCIONARIO(NOME_FUNCIONARIO,USUARIO,SENHA) VALUES('WELLINGTON','WELL','1234567')